module = 'test.basic'

[[cells]]
lang = 'python'
code = '''
name: str = 'zheng'
print(f'hello, {name}')
return name
'''

[[cells]]
name = 'abc'
# default lang is python
lang = 'python'
code = '''
a: int = 5
print('hello')
return 5
'''


[[cells]]
lang = 'cmd'
code = 'ls'

[[cells]]
lang = 'shell'
code = 'which ls; ls -l xyz'
env = 'HOME RUN_PATH'

[[cells]]
code = 'print("hi")'

